// @generated by expo-module-scripts
const { defineConfig } = require('eslint/config');
const baseConfig = require('expo-module-scripts/eslint.config.base');

module.exports = defineConfig([
  baseConfig,
  {
    ignores: ['build/**', 'plugin/build/**', 'example/**'],
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': 'warn',
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
]);
